Lab_Working_1/Lab/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from Pathology import views

urlpatterns = [
     path('admin/', admin.site.urls),
     path('', views.home, name='home'),
     path('register/', views.register, name='register'),
     path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
     path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
     path('patient/', views.patient_details_view, name='patient'),
     path('image_upload/', views.image_upload_view, name='image_upload'),
     path('image_upload/<test_name>', views.image_upload_view, name='test_name'),
     path('report/', views.report_view, name='report'),
     path('location/', views.location_view, name='location'),
     path('test/', views.test_in_pathology, name='test'),
     path('final_report/', views.final_reports_view, name='final_report'),
     #path('blood_test/', views.blood_test_view, name='blood_test'),
     #path('urine_test/', views.urine_test_view, name='urine_test'),
     path('add_test/', views.test_view, name='add_test'),
     path('about_us/', views.about_us, name='about_us'),
     path('contact_us/', views.contact_us, name='contact_us'),
     #path('new/', views.new_view, name = 'new'),
     # path('name/', views.name_view, name='name')

]

Lab_Working_1/Pathology/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from multiselectfield import MultiSelectField
from Pathology.choices import *


class Patient_Details(models.Model):
    Name = models.CharField(max_length=100, unique=True)
    Age = models.PositiveIntegerField()
    Gender = models.CharField(max_length=120, choices=GENDER_CHOICES)
    phone = models.CharField(max_length=10, unique=True)
    time = models.DateTimeField(default=datetime.now(), blank=True)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.Name)


class Image_Input(models.Model):
    # patient_details = models.ForeignKey(Patient_Details, on_delete='CASCADE', default='')
    Image_Upload = models.FileField(upload_to='Patient_reports/')
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.Image_Upload)


class Scripts(models.Model):
    api_url = models.URLField(default='')
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.api_url


class AI_Usecase_Occurences(models.Model):
    time = models.DateTimeField(default=datetime.now(), blank=True)
    Image_Output_1 = models.FileField(default='')
    confidence = models.CharField(max_length=5, default='')
    heatmap = models.FileField(default='')
    # Image_Output_2 = models.FileField()
    # Image_Output_3 = models.FileField()
    # Image_Output_4 = models.FileField()
    # Image_Output_5 = models.FileField()
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.Image_Output_1) + "-" + str(self.confidence)


class Location(models.Model):
    location = models.CharField(max_length=1000)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.location)


class Test_Pathology(models.Model):
    some_test = models.CharField(max_length=500)
    api_url = models.URLField()

    # patient = models.ForeignKey(Patient_Details, on_delete='CASCADE', default='')
    # user = models.ForeignKey(User,null=True, on_delete='CASCADE')

    def __str__(self):
        return str(self.some_test)


class Reports(models.Model):
    patient_details = models.ForeignKey(Patient_Details, on_delete=models.CASCADE)
    test = models.ForeignKey(Test_Pathology, on_delete=models.CASCADE, default='')
    image_output = models.ForeignKey(AI_Usecase_Occurences, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, default='')
    description = models.CharField(max_length=1000)
    # image_output = models.CharField(max_length=2000)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.description)


class Test(models.Model):
    test = models.CharField(max_length=500, unique=True)

    # script = models.ForeignKey(Scripts, on_delete='CASCADE', null=True)

    def __str__(self):
        return str(self.test)


class Lab_Api(models.Model):
    test = models.ForeignKey(Test_Pathology, on_delete=models.CASCADE, default='')
    # api_name = models.CharField(max_length=100)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.test)


class Lab_Api_Scripts(models.Model):
    lab_api = models.ForeignKey(Lab_Api, on_delete=models.CASCADE)
    scripts = models.ForeignKey(Scripts, on_delete=models.CASCADE)
    lab_api_scripts_name = models.CharField(max_length=100)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.lab_api_scripts_name)


class Lab_Api_On_Image_Input(models.Model):
    lab_api = models.ForeignKey(Lab_Api, on_delete=models.CASCADE)
    image_input = models.ForeignKey(Image_Input, on_delete=models.CASCADE)
    lab_api_on_image_input_name = models.CharField(max_length=100)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.lab_api_on_image_input_name)

Lab_Working_1/Pathology/forms.py
from django import forms
from Pathology.models import *
from Pathology.choices import *


class Patient_Details_Form(forms.ModelForm):
    Gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect())
    phone = forms.RegexField(regex=r'^\+?1?\d{9,10}$')

    class Meta:
        model = Patient_Details
        fields = ['Name', 'Age', 'Gender', 'phone', 'time']


class Image_Input_Forms(forms.ModelForm):
    class Meta:
        model = Image_Input
        fields = ['Image_Upload']


class Reports_Form(forms.ModelForm):
    class Meta:
        model = Reports
        fields = ['location', 'patient_details', 'test', 'image_output']


class Location_Form(forms.ModelForm):
    class Meta:
        model = Location
        fields = ['location']


# class Blood_Test_Form(forms.ModelForm):
#   class Meta:
#      model = Blood_Test
#     fields = ['blood_test']


# class Urine_Test_Form(forms.ModelForm):
#   class Meta:
#      model = Urine_Test
#     fields = ['urine_test']


class Test_Form(forms.ModelForm):
    class Meta:
        model = Test_Pathology
        fields = ['some_test']


class Test_Pathology_Form(forms.ModelForm):
    # blood = forms.ModelMultipleChoiceField(queryset = Blood_Test.objects.all(), widget=forms.CheckboxSelectMultiple)
    # urine = forms.ModelMultipleChoiceField(queryset = Urine_Test.objects.all(), widget=forms.CheckboxSelectMultiple)
    test1 = forms.ModelMultipleChoiceField(queryset=Test_Pathology.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Test_Pathology
        fields = ['test1']

# class Name_Form(forms.ModelForm):
#     class Meta:
#         model = Name
#         fields = ['some_text']

Lab_Working_1/Pathology/views.py
import datetime
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from Pathology.GetValueFromPowerAI import *
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from Pathology.forms import *


def home(request):
    return render(request, 'Home.html')


def about_us(request):
    return render(request, 'About_Us.html')


def contact_us(request):
    return render(request, 'Contact_Us.html')


def test_in_pathology(request):
    test_list = []
    patient_name = ''
    global len_value
    global value
    if request.method == 'POST':
        print('in post')
        value = request.POST.getlist('test')
        len_value = len(value)
        print(len_value)
        print(value)
        return HttpResponseRedirect('/image_upload/')

    else:
        tests = Test_Pathology.objects.all()
        for test in tests:
            test_list.append(test)
        patients = Patient_Details.objects.all()
        length = len(patients) - 1
        print(length)
        patient_name = patients[length]
        print(patient_name)

    return render(request, 'test_in_pathology.html', {'tests': test_list, 'patient_name': patient_name})


def report_view(request):
    test_list = []
    # if request.method == 'POST':
    # form = Reports_Form(request.POST)
    # if form.is_valid():
    #     form.save()
    location = Location.objects.all()
    loc_length = len(location) - 1
    l1 = location[loc_length]

    # Patient = Patient_Details.objects.all()
    # p_length = len(Patient) - 1
    # p1 = Patient[p_length]

    results = AI_Usecase_Occurences.objects.all().values_list('Image_Output_1', flat=True)
    conf = AI_Usecase_Occurences.objects.all().values_list('confidence', flat=True)
    heatmap = AI_Usecase_Occurences.objects.all().values_list('heatmap', flat=True)
    results_list = list(results)
    conf_list = list(conf)
    heat_list = list(heatmap)
    # len_results_list = len(results_list)

    value

    for i in value:
        print(i)

    newlist = results_list[-len_value:]
    confList = conf_list[-len_value:]
    heatList = heat_list[-len_value:]

    # for n in newlist:
    #     print(n)

    #     return HttpResponseRedirect('/final_report/')
    # else:
    tests = Test_Pathology.objects.all()
    for test in tests:
        test_list.append(test)
    patients = Patient_Details.objects.all()
    length = len(patients) - 1
    print(length)
    patient_name = patients[length]
    print(patient_name)

    # form = Reports_Form()

    # return render(request, 'report.html', {'form': form})
    return render(request, 'report.html',
                  {'heatList': heatList, 'confList': confList, 'newlist': newlist, 'value': value, 'patient_name': patient_name,
                   'Location': l1})  # {'Location': l1, 'Patient':p1}   #, 'tests': test_list,


def image_upload_view(request):
    test_list = []
    if request.method == 'POST':
        form = Image_Input_Forms(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            global url
            value
            for val in value:
                test = Test_Pathology.objects.get(some_test='{0}'.format(val))
                url = test.api_url
                # print(test)
                # print(url)
                length = len(Image_Input.objects.all())
                image = Image_Input.objects.filter(id=length)
                for img in image:
                    img = str(img)
                    sli = slice(16, -1)
                    img = img[sli] + "g"
                    # filename = '/home/kernel/Lab_Working_1/media/Patient_reports/' + img
                    import os
                cwd = '/home/kernel/shazan/11dec2019/Lab_Working_1/media/Patient_reports/'
                filename = cwd + img
                # 'E:\Lab_Working_1\media\Patient_reports\' + img
                output = detect_image_label(filename, url)
                print('new', output)
                conf = str(output[2])
                # Reports.objects.create(location_id=1, patient_details_id='1', image_output=output[1], description='report_description', test_id=1)

                # / home / kernel / shazan / 11
                # dec2019 / Lab_Working_1 / Pathology / static / heatmap

                import urllib.request
                urllib.request.urlretrieve(output[3], "/home/kernel/shazan/11dec2019/Lab_Working_1/Pathology/static/heatmap/heatmap.png")

                AI_Usecase_Occurences.objects.create(time=datetime.now(), Image_Output_1=output[1], confidence=conf,
                                                     heatmap="/home/kernel/shazan/11dec2019/Lab_Working_1/Pathology/static/heatmap/heatmap.png")
            return redirect('/report/')
    else:
        tests = Test_Pathology.objects.all()
        for test in tests:
            test_list.append(test)
        patients = Patient_Details.objects.all()
        length = len(patients) - 1
        print(length)
        patient_name = patients[length]
        print(patient_name)
        form = Image_Input_Forms()

    return render(request, 'Image_Upload.html', {'form': form, 'patient_name': patient_name})


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/login/')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})


@login_required
def patient_details_view(request):
    if request.method == 'POST':
        form = Patient_Details_Form(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/test/')
    else:
        form = Patient_Details_Form()

    return render(request, 'patient_details.html', {'form': form})


def final_reports_view(request):
    # patient = Patient_Details.objects.all()
    # reports = Reports.objects.all()
    # length_report = len(reports) - 1
    # length_patient = len(patient) - 1
    # patient_name = patient[length_patient]
    # print(patient_name)
    # print('------------------------------------------')
    # print(reports[length_report])
    # context = {
    #     'reports': reports[length_report],
    #     'patient': patient_name
    # }
    return render(request, 'final_report_view.js')


def location_view(request):
    if request.method == 'POST':
        form = Location_Form(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/report/')
    else:
        form = Location_Form()

    return render(request, 'location.html', {'form': form})


def test_view(request):
    if request.method == 'POST':
        form = Test_Form(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/test/')
    else:
        form = Test_Form()
    return render(request, 'test.html', {'form': form})

# def blood_test_view(request):
#     if request.method == 'POST':
#         form = Blood_Test_Form(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('/test/')
#     else:
#         form = Blood_Test_Form()
#     return render(request, 'blood_test_view.html', {'form': form})
#
#
# def urine_test_view(request):
#     if request.method == 'POST':
#         form = Urine_Test_Form(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('/test/')
#     else:
#         form = Urine_Test_Form()
#     return render(request, 'urine_test_view.html', {'form': form})

# def Image_upload_view(request):
#     # print(test_name)
#     if request.method == 'POST':
#         form = Image_Input_Forms(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             length = len(Image_Input.objects.all())
#             image = Image_Input.objects.filter(id=length)
#             for img in image:
#                 img = str(img)
#                 sli = slice(16, -1)
#                 img = img[sli] + "g"
#             filename = '/home/siraj/Lab/media/Patient_reports/' + img
#             output = detect_image_label(filename)
#             Reports.objects.create(location_id=1, patient_details_id='1', image_output=output[1], description='report_description', test_id=1)
#             AI_Usecase_Occurences.objects.create(time=datetime.now(), Image_Output_1=output[0] + "-" + output[1])
#             return redirect('/report/')
#     else:
#         form = Image_Input_Forms()
#
#     return render(request, 'Image_Upload.html', {'form': form})


# def new_view(request):
#     test_f = Test.objects.all()
#     length_test= len(test_f)
#     latest_test = length_test - 1
#     b = test_f[latest_test]
#     return b(

# def new_view(request):
#     script = Lab_Api.objects.get
#     if request.method == 'POST':
#         form = Image_Input_Forms(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             length = len(Image_Input.objects.all())
#             image = Image_Input.objects.filter(id=length)
#             for img in image:
#                 img = str(img)
#                 sli = slice(16, -1)
#                 img = img[sli] + "g"
#                 filename = '/home/siraj/Lab/media/Patient_reports/' + img
#                 output = detect_image_label(filename, test_link)
#                 # Reports.objects.create(location_id=1, patient_details_id='1', image_output=output[1], description='report_description', test_id=1)
#                 AI_Usecase_Occurences.objects.create(time=datetime.now(), Image_Output_1=output[0] + "-" + output[1])
#                 return redirect('/report/')
#         else:
#             form = Image_Input_Forms()
#

Lab_Working_1/Pathology/templates/About_Us.html
{% load static %}

<head>
    <title>About Us</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<style type="text/css">
<!--    *{-->
<!--    margin: 0;-->
<!--    padding: 0;-->
<!--}-->

body{
    background-image: url({% static '/Images/Medicalimage.jpg' %});
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    background-attachment: fixed;
}

.container{
    height:100%;
    width:100%;
    background-position: center;
    background-size: cover;
    position: absolute;
    margin: 0 10% 0 7% auto;

}

.card{
    width: 1000px;
    heigth: 480px;
    position: center;
    margin: 5% 0 10% 0;
    padding: 5px;
    background-color: rgba(0,0,0, 0.1);

}

.card-body {
    width: 1000px;
    padding: 10px;
    position: left;
    margin: 0 0 0 0;
}

#mydiv{
    margin : 10% 0 0 3%;
    font-family: sans-serif;
    font-size: 19px;
    color: black;
}

</style>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
    <a class="navbar-brand" href=#><i class='fa fa-clinic-medical'></i>Doctor App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-around" id="navbarSupportedContent">
        <ul class="navbar-nav mc-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;Home </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'about_us' %}"><i class="fa fa-info-circle" aria-hidden="true"></i>&nbsp;About
                    Us</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact_us' %}"><i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;Contact
                    Us</a>
            </li>

            {% if user.is_authenticated %}

            <li class="nav-item ">
                <a class="nav-link" href="{% url 'patient' %}"><i class="fa fa-bed" aria-hidden="true"></i>Patient
                    Details</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;Log
                    out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Sign
                    Up</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Log
                    In</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div id="mydiv">
    <p>We are the largest Pathology laboratory in Dubai and providing superior quality pathology services <br> to its
        patients through a very efficient network of labs and collection points.<br>
        We have a qualified team of pathology specialists with doctorate degrees.<br>
        We offer patients convenient locations for their diagnostic laboratory services and efficient service.
    </p>
    <ul>
        <li>24 hour Laboratory service</li>
        <li>24 hour Pharmacy</li>
        <li>Diagnostics CT, MRI, X-Ray</li>
        <li>Life-saving equipments</li>
        <li>Patient Care and Ambulance Services</li>
        <li>Operating theaters of World Class Standard</li>
        <li>Team of Pathology Specialists</li>
    </ul>
</div>
</body>

Lab_Working_1/Pathology/templates/Contact_Us.html
{% load static %}
<head>
    <title>About Us</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <style>
        #mydiv{
    margin : 10% 0 0 3%;
    font-family: sans-serif;
    font-size: 19px;
    color: black;
}

body{
    background-image: url({% static '/Images/Medicalimage.jpg' %});
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    background-attachment: fixed;
}


    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
    <a class="navbar-brand" href=#><i class='fa fa-clinic-medical'></i>Doctor App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-around" id="navbarSupportedContent">
        <ul class="navbar-nav mc-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;Home </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about_us' %}"><i class="fa fa-info-circle" aria-hidden="true"></i>&nbsp;About
                    Us</a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'contact_us' %}"><i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;Contact
                    Us</a>
            </li>

            {% if user.is_authenticated %}

            <li class="nav-item ">
                <a class="nav-link" href="{% url 'patient' %}"><i class="fa fa-bed" aria-hidden="true"></i>Patient
                    Details</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;Log
                    out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Sign
                    Up</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Log
                    In</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div id="mydiv">
    <strong style="text-align:center;">Contact Info:</strong>
    <p></p>
    <p>Port Rashid Road, Al Mankhool Area, Bur Dubai,</p>
    <p><strong><i class="fa fa-phone" aria-hidden="true"></i>  Phone</strong>: 04 000 0000</p>
</div>
</body>

Lab_Working_1/Pathology/templates/Home.html
{% load static %}
<html>
<head>
    <title>Home Page</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
    <a class="navbar-brand" href=#><i class='fa fa-clinic-medical'></i>Doctor App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-around" id="navbarSupportedContent">
        <ul class="navbar-nav mc-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;Home </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about_us' %}"><i class="fa fa-info-circle" aria-hidden="true"></i>&nbsp;About
                    Us</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact_us' %}"><i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;Contact
                    Us</a>
            </li>

            {% if user.is_authenticated %}

            <li class="nav-item ">
                <a class="nav-link" href="{% url 'patient' %}"><i class="fa fa-bed" aria-hidden="true"></i>Patient
                    Details</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;Log
                    out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Sign
                    Up</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Log
                    In</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container-main">
    <!--        <img src="{% static 'Images/Medicalimage.jpg' %}" alt="no image">-->
    <div class="row-wrap">
        <div class="row">
            <!--                    <h1 class=" title text-center">Hello Shazan!</h1>-->
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
</body>
</html>

Lab_Working_1/Pathology/templates/location.html
{% extends 'base.html' %}
{% block body %}
{% load crispy_forms_tags %}
    <h2 class="title">Location</h2><br>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary" >Submit</button>
    </form>
{% endblock %}

Lab_Working_1/Pathology/templates/test_in_pathology.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!--<script src="{% static 'js/js.js' %}"></script>-->
<form method='post'>
    {% csrf_token %}
    <tr>
        <th><label><b>{{ patient_name }}</b></label></th>
        <td>
            <ul id="id_test1">
                {% for test in tests %}
                <li><label for="id_test1_0"><input type="checkbox" name="test" value="{{ test }}" id="id_test1_0">
                    {{ test }}</label>
                </li>
                {% endfor %}
            </ul>
        </td>
    </tr>

    Do you want to add test?<a href="{% url 'add_test' %}">Click here</a><br>
    <button type="submit" , class="btn btn-primary btn-sm" onclick="getSelectedValue()">Submit</button>
</form>
{% endblock %}